// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mersikovs/gomart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AccrualClient is an autogenerated mock type for the AccrualClient type
type AccrualClient struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields: ctx, orderNumber
func (_m *AccrualClient) GetOrder(ctx context.Context, orderNumber string) (*model.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccrualClient creates a new instance of AccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualClient {
	mock := &AccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
