// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mersikovs/gomart/internal/model"
	mock "github.com/stretchr/testify/mock"

	service "github.com/mersikovs/gomart/internal/service"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// OrderList provides a mock function with given fields: ctx, userID
func (_m *OrderService) OrderList(ctx context.Context, userID int64) ([]model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for OrderList")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *OrderService) RegisterOrder(ctx context.Context, userID int64, orderNumber string) (service.OrderProcessStatus, error) {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrder")
	}

	var r0 service.OrderProcessStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (service.OrderProcessStatus, error)); ok {
		return rf(ctx, userID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) service.OrderProcessStatus); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		r0 = ret.Get(0).(service.OrderProcessStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterWithdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *OrderService) RegisterWithdraw(ctx context.Context, userID int64, orderNumber string, sum int) (service.OrderProcessStatus, error) {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWithdraw")
	}

	var r0 service.OrderProcessStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) (service.OrderProcessStatus, error)); ok {
		return rf(ctx, userID, orderNumber, sum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) service.OrderProcessStatus); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Get(0).(service.OrderProcessStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int) error); ok {
		r1 = rf(ctx, userID, orderNumber, sum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawList provides a mock function with given fields: ctx, userID
func (_m *OrderService) WithdrawList(ctx context.Context, userID int64) ([]model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawList")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
