// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mersikovs/gomart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *Storage) CreateOrder(ctx context.Context, userID int64, orderNumber string) (*model.Order, error) {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.Order, error)); ok {
		return rf(ctx, userID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.Order); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, login, password
func (_m *Storage) CreateUser(ctx context.Context, login string, password string) (int64, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWithdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *Storage) CreateWithdraw(ctx context.Context, userID int64, orderNumber string, sum int) (*model.Order, error) {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithdraw")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) (*model.Order, error)); ok {
		return rf(ctx, userID, orderNumber, sum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int) *model.Order); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int) error); ok {
		r1 = rf(ctx, userID, orderNumber, sum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *Storage) FindUserByID(ctx context.Context, id int64) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByLogin provides a mock function with given fields: ctx, login
func (_m *Storage) FindUserByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLogin")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByNumber provides a mock function with given fields: ctx, orderNumber
func (_m *Storage) GetOrderByNumber(ctx context.Context, orderNumber string) (*model.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByStatus provides a mock function with given fields: ctx, status, action
func (_m *Storage) GetOrdersByStatus(ctx context.Context, status string, action model.ActionType) ([]model.Order, error) {
	ret := _m.Called(ctx, status, action)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByStatus")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ActionType) ([]model.Order, error)); ok {
		return rf(ctx, status, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ActionType) []model.Order); ok {
		r0 = rf(ctx, status, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.ActionType) error); ok {
		r1 = rf(ctx, status, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUser provides a mock function with given fields: ctx, id, action
func (_m *Storage) GetOrdersByUser(ctx context.Context, id int64, action model.ActionType) ([]model.Order, error) {
	ret := _m.Called(ctx, id, action)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUser")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.ActionType) ([]model.Order, error)); ok {
		return rf(ctx, id, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, model.ActionType) []model.Order); ok {
		r0 = rf(ctx, id, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, model.ActionType) error); ok {
		r1 = rf(ctx, id, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatusAndUserBalance provides a mock function with given fields: ctx, userID, orderNumber, status, sum
func (_m *Storage) UpdateOrderStatusAndUserBalance(ctx context.Context, userID int64, orderNumber string, status model.OrderStatus, sum int) error {
	ret := _m.Called(ctx, userID, orderNumber, status, sum)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatusAndUserBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, model.OrderStatus, int) error); ok {
		r0 = rf(ctx, userID, orderNumber, status, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
